/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author jilly
 */
public class HangmanUI extends javax.swing.JFrame
{

    /**
     * Creates new form HangmanUI
     */
    public HangmanUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wordDisplay = new javax.swing.JTextArea();
        wrongAnswersProgressBar = new javax.swing.JProgressBar();
        subHead1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        worngAnswersDisplay = new javax.swing.JTextArea();
        htpButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        subHead2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        letterGuess = new javax.swing.JTextArea();
        answerButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Juice ITC", 1, 48)); // NOI18N
        title.setText("FInd the Password");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        wordDisplay.setEditable(false);
        wordDisplay.setColumns(20);
        wordDisplay.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        wordDisplay.setForeground(new java.awt.Color(18, 30, 49));
        wordDisplay.setRows(5);
        wordDisplay.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(wordDisplay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 100));
        getContentPane().add(wrongAnswersProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 20));

        subHead1.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        subHead1.setText("Wrong letters");
        getContentPane().add(subHead1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        worngAnswersDisplay.setColumns(20);
        worngAnswersDisplay.setRows(5);
        jScrollPane1.setViewportView(worngAnswersDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 80));

        htpButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        htpButton.setText("How to play");
        getContentPane().add(htpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 30));

        homeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        homeButton.setText("Home");
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        subHead2.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        subHead2.setText("Letter Guess");
        getContentPane().add(subHead2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 20));

        letterGuess.setColumns(20);
        letterGuess.setRows(5);
        jScrollPane3.setViewportView(letterGuess);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, -1));

        answerButton.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        answerButton.setText("TEST LETTER");
        getContentPane().add(answerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jewelryBoxClosed.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton htpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea letterGuess;
    private javax.swing.JLabel subHead1;
    private javax.swing.JLabel subHead2;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea wordDisplay;
    private javax.swing.JTextArea worngAnswersDisplay;
    private javax.swing.JProgressBar wrongAnswersProgressBar;
    // End of variables declaration//GEN-END:variables
}
