/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Backend.*;
/**
 *
 * @author jilly
 */
public class OptionsUI extends javax.swing.JFrame
{

    /**
     * Creates new form OptionsUI
     */
    public OptionsUI()
    {
        initComponents();
        
        //setting the background of buttons to be transparent
        brokenPictureFramesOption.setOpaque(false);
        brokenPictureFramesOption.setContentAreaFilled(false);
        brokenPictureFramesOption.setBorderPainted(false);
        
        musicBoxOption.setOpaque(false);
        musicBoxOption.setContentAreaFilled(false);
        musicBoxOption.setBorderPainted(false);
        
        doorOption.setOpaque(false);
        doorOption.setContentAreaFilled(false);
        
        tornUpPicturesOption.setOpaque(false);
        tornUpPicturesOption.setContentAreaFilled(false);
        
        
        //setting all the option variables to false (variables in Screenmethods)
        ScreenMethods.resetOptionVariables();    
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        informationLabel = new javax.swing.JLabel();
        brokenPictureFramesOption = new javax.swing.JButton();
        musicBoxOption = new javax.swing.JButton();
        doorOption = new javax.swing.JButton();
        tornUpPicturesOption = new javax.swing.JButton();
        DataSheetButton = new javax.swing.JButton();
        SaveExitButton = new javax.swing.JButton();
        musicBoxLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tornUpPicturesLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informationLabel.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        informationLabel.setText("Pick what you would like to investigate");
        getContentPane().add(informationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        brokenPictureFramesOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brokenPictureFrameOriginal.jpg"))); // NOI18N
        brokenPictureFramesOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                brokenPictureFramesOptionActionPerformed(evt);
            }
        });
        getContentPane().add(brokenPictureFramesOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 30, 40));

        musicBoxOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/musicBox.png"))); // NOI18N
        musicBoxOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                musicBoxOptionActionPerformed(evt);
            }
        });
        getContentPane().add(musicBoxOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, 80));

        doorOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                doorOptionActionPerformed(evt);
            }
        });
        getContentPane().add(doorOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 170));

        tornUpPicturesOption.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tornUpPicturesOptionActionPerformed(evt);
            }
        });
        getContentPane().add(tornUpPicturesOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 160, 40));

        DataSheetButton.setText("Data sheet");
        DataSheetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DataSheetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DataSheetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        SaveExitButton.setText("Save and exit");
        SaveExitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        musicBoxLabel.setText("Music box");
        getContentPane().add(musicBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 20));

        jLabel2.setText("Broken frame");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 175, -1, 20));

        jLabel3.setText("Door");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        tornUpPicturesLabel.setText("Torn up pictures");
        getContentPane().add(tornUpPicturesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brokenDownRoom.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //ACTIONS PERFORMED
    //options
    private void musicBoxOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_musicBoxOptionActionPerformed
    {//GEN-HEADEREND:event_musicBoxOptionActionPerformed
        //setting the musicBoxOption variable to true
        ScreenMethods.musicBoxOption = true;
        //opening the screens
        new HangmanUI().setVisible(true);
        new HowToPlay().setVisible(true); 
        //disposing this screen
        this.dispose();
    }//GEN-LAST:event_musicBoxOptionActionPerformed

    private void brokenPictureFramesOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_brokenPictureFramesOptionActionPerformed
    {//GEN-HEADEREND:event_brokenPictureFramesOptionActionPerformed
        //setting the brokenPictureFrames variable to true
        ScreenMethods.brokenPictureFramesOption = true;
        //opening the screens
        new BrokenPictureFramesRiddle().setVisible(true);
        new HowToPlay().setVisible(true); 
        //disposing this screen
        this.dispose();
    }//GEN-LAST:event_brokenPictureFramesOptionActionPerformed

    private void doorOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_doorOptionActionPerformed
    {//GEN-HEADEREND:event_doorOptionActionPerformed
        //setting the door variable to true
        ScreenMethods.doorOption = true;
        //opening the screens
        //new BrokenPictureFramesRiddle().setVisible(true);       
        new HowToPlay().setVisible(true); 
        //disposing this screen
        this.dispose();
    }//GEN-LAST:event_doorOptionActionPerformed

    private void tornUpPicturesOptionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tornUpPicturesOptionActionPerformed
    {//GEN-HEADEREND:event_tornUpPicturesOptionActionPerformed
         //setting the tornUpPicturesOption variable to true
        ScreenMethods.tornUpPicturesOption = true;
        //opening the screens
        new PuzzleUI().setVisible(true);
        new HowToPlay().setVisible(true);
        //disposing this screen
        this.dispose();
    }//GEN-LAST:event_tornUpPicturesOptionActionPerformed

    //game options
    private void DataSheetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DataSheetButtonActionPerformed
    {//GEN-HEADEREND:event_DataSheetButtonActionPerformed
        
    }//GEN-LAST:event_DataSheetButtonActionPerformed

    private void SaveExitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveExitButtonActionPerformed
    {//GEN-HEADEREND:event_SaveExitButtonActionPerformed
        
    }//GEN-LAST:event_SaveExitButtonActionPerformed

    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OptionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OptionsUI().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DataSheetButton;
    private javax.swing.JButton SaveExitButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton brokenPictureFramesOption;
    private javax.swing.JButton doorOption;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel musicBoxLabel;
    private javax.swing.JButton musicBoxOption;
    private javax.swing.JLabel tornUpPicturesLabel;
    private javax.swing.JButton tornUpPicturesOption;
    // End of variables declaration//GEN-END:variables
}
