/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author jilly
 */
public class BrokenPictureFramesRiddle extends javax.swing.JFrame
{

    /**
     * Creates new form BrokenPictureFramesRiddle
     */
    public BrokenPictureFramesRiddle()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        RiddlePanel = new javax.swing.JScrollPane();
        Riddle = new javax.swing.JTextArea();
        UserAnswerPanel = new javax.swing.JScrollPane();
        Answer = new javax.swing.JTextArea();
        Instruction = new javax.swing.JLabel();
        AnswerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Riddle.setEditable(false);
        Riddle.setColumns(20);
        Riddle.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        Riddle.setRows(5);
        Riddle.setText("You carefully blow away the dust that was on the \npicture frame. The engraving reads:\n\nI sit opposite the 1 when you look at me and when\nI am square the sum of my numbers is 13. I am an \n\"even\" number, but I am also odd.\nWhat number am I?");
        Riddle.setWrapStyleWord(true);
        Riddle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RiddlePanel.setViewportView(Riddle);

        Answer.setColumns(20);
        Answer.setRows(5);
        UserAnswerPanel.setViewportView(Answer);

        Instruction.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        Instruction.setText("Type answer in box below:");
        Instruction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        AnswerButton.setText("Answer");
        AnswerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnswerButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UserAnswerPanel)
                        .addComponent(RiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                        .addComponent(Instruction)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Instruction)
                .addGap(2, 2, 2)
                .addComponent(UserAnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerButton)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AnswerButtonActionPerformed
    {//GEN-HEADEREND:event_AnswerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Answer;
    private javax.swing.JButton AnswerButton;
    private javax.swing.JLabel Instruction;
    private javax.swing.JTextArea Riddle;
    private javax.swing.JScrollPane RiddlePanel;
    private javax.swing.JScrollPane UserAnswerPanel;
    // End of variables declaration//GEN-END:variables
}
