/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Backend.UserManager;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author megan
 */
public class UserScreen extends javax.swing.JFrame
{
    /**
     * Creates new form UserScreen
     */
    public UserScreen()
    {
        initComponents();
        //populating the list with the users
        UserManager users = new UserManager();
        ArrayList<String> usersNames = users.getListNames();
        DefaultListModel listModel = new DefaultListModel();
        listModel.addAll(usersNames);
        userList.setModel(listModel);
        //setting it to be in the centre of the screen
        setLocationRelativeTo (null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        title = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        selectUserMessage = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("THE HOUSE OF MYSTERIES");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, 72));

        loadButton.setBackground(new java.awt.Color(48, 29, 39));
        loadButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loadButton.setForeground(new java.awt.Color(114, 214, 206));
        loadButton.setText("LOAD");
        loadButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 120, -1));

        exitButton.setBackground(new java.awt.Color(48, 29, 39));
        exitButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(114, 214, 206));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, -1));

        newUserButton.setBackground(new java.awt.Color(48, 29, 39));
        newUserButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        newUserButton.setForeground(new java.awt.Color(114, 214, 206));
        newUserButton.setText("NEW USER");
        newUserButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, -1));

        deleteButton.setBackground(new java.awt.Color(48, 29, 39));
        deleteButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(114, 214, 206));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, -1));

        userList.setBackground(new java.awt.Color(48, 29, 39));
        userList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        userList.setForeground(new java.awt.Color(114, 214, 206));
        userList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(userList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 190));

        selectUserMessage.setBackground(new java.awt.Color(48, 29, 39));
        selectUserMessage.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        selectUserMessage.setForeground(new java.awt.Color(250, 0, 0));
        selectUserMessage.setToolTipText("");
        selectUserMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(selectUserMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserSceen.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //closes the game
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    
    //gets the data of the user and loads the game
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadButtonActionPerformed
    {//GEN-HEADEREND:event_loadButtonActionPerformed
        //checking if a user was selected
        if(userList.isSelectionEmpty())
        {
            selectUserMessage.setText("Please select a user");
            selectUserMessage.setOpaque(true);
        } else
        {
            //getting the selected index of the user
            UserManager.setCurrentUserIndex(userList.getSelectedIndex());
            //opens the game and closes this screen
            new OptionsScreen().setVisible(true); // will change when there is a new room to go to
            this.dispose();
        }        
    }//GEN-LAST:event_loadButtonActionPerformed

    
    //opens the userAdderScreen
    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newUserButtonActionPerformed
    {//GEN-HEADEREND:event_newUserButtonActionPerformed
        new NewUserScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newUserButtonActionPerformed

    //deletes the user selected from the user array
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteButtonActionPerformed
    {//GEN-HEADEREND:event_deleteButtonActionPerformed
        UserManager userArray = new UserManager();
        userArray.delete(userList.getSelectedIndex());
        
        //refreshing the list
        UserManager users = new UserManager();
        ArrayList<String> usersNames = users.getListNames();
        DefaultListModel listModel = new DefaultListModel();
        listModel.addAll(usersNames);
        userList.setModel(listModel);
    }//GEN-LAST:event_deleteButtonActionPerformed

   //main method
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JLabel selectUserMessage;
    private javax.swing.JLabel title;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
